version: '2.2'

volumes:
  redis-data:
     driver: local
  yii-db:
    driver: local

services:
    web:
      image: trydirect/yii2-restful:2.0
      build: dockerfiles/build
      container_name: web
      restart: always
      entrypoint: /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf -n
      env_file: .env
      links:
        - db
      depends_on:
        - db
      volumes:
        - ./backend:/var/www/backend
        - ./configs/php/xdebug.ini:/usr/local/lib/php/doc/xdebug/xdebug.ini
        - ./configs/php/php.ini:/usr/local/etc/php.ini
        - ./configs/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

    nginx:
      image: nginx:latest
      container_name: nginx
      restart: always
      depends_on:
        - web
      links:
        - web
        - kibana
      ports:
        - "80:80"
        - "443:443"
      volumes_from:
        - web
      volumes:
        - ./configs/nginx/conf.d:/etc/nginx/conf.d/
        - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf

    db:
      image: mysql:5.7
      container_name: db
      restart: always
      env_file:
        - .env
      volumes:
        - yii-db:/var/lib/mysql

    mq:
      image: rabbitmq:3-management
      restart: always
      container_name: mq
      env_file:
        - .env
      ports:
        - "5672:5672"
        - "21072"

    redis:
      image: redis:latest
      restart: always
      container_name: redis
      env_file:
        - .env
      volumes:
        - redis-data:/data

    elasticsearch:
      build: ./configs/elastic
      restart: always
      container_name: elasticsearch
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        discovery.type: "single-node"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      links:
        - web
      depends_on:
        - web
      volumes:
        - ./elasticsearch/data:/usr/share/elasticsearch/data

    kibana:
        image: kibana:5.4.3
        restart: always
        container_name: kibana
        ports:
          - "5601:5601"
        links:
          - elasticsearch
        environment:
          ELASTICSEARCH_URL: http://elasticsearch:9200
        volumes:
          - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

    logstash:
        build: ./configs/logstash
        container_name: logstash
        restart: always
        environment:
          LS_JAVA_OPTS: "-Xms1g -Xmx4g"
        ports:
          - "5044"
        depends_on:
          - elasticsearch
        links:
          - elasticsearch